:concurrency: 3
:timeout: 8 # heroku
:verbose: true
:queues: # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
  #- active_storage_analysis
  #- active_storage_purge
